1.6  Part 1: Multiple Linear Regression Modeling
I'm running a normality plot on the prices to review the validity of regression.

1
places2 = places.iloc[1:1850, 3:48]
2
newprice = places['Price']
3
model1 = smf.ols("Price~UID+Area+Region+Bedrooms+Resale+MaintenanceStaff+Gymnasium+SwimmingPool+LandscapedGardens+JoggingTrack+RainWaterHarvesting+IndoorGames+ShoppingMall+Intercom+SportsFacility+ATM+ClubHouse+School+X24X7Security+PowerBackup+CarParking+StaffQuarter+Cafeteria+MultipurposeRoom+Hospital+WashingMachine+Gasconnection+AC+Wifi+Childrensplayarea+LiftAvailable+BED+VaastuCompliant+Microwave+GolfCourse+TV+DiningTable+Sofa+Wardrobe+Refrigerator+Furniture+Fitness+Appliances+Entertain",data=places).fit()
4
model1.summary()
OLS Regression Results
Dep. Variable:	Price	R-squared:	0.867
Model:	OLS	Adj. R-squared:	0.864
Method:	Least Squares	F-statistic:	311.5
Date:	Sun, 10 Oct 2021	Prob (F-statistic):	0.00
Time:	16:18:17	Log-Likelihood:	-31195.
No. Observations:	1856	AIC:	6.247e+04
Df Residuals:	1817	BIC:	6.268e+04
Df Model:	38		
Covariance Type:	nonrobust		
coef	std err	t	P>|t|	[0.025	0.975]
Intercept	-6.929e+06	7.48e+05	-9.259	0.000	-8.4e+06	-5.46e+06
Region[T.East]	-1.104e+06	4.65e+05	-2.372	0.018	-2.02e+06	-1.91e+05
Region[T.North]	6.022e+05	4.77e+05	1.263	0.207	-3.33e+05	1.54e+06
Region[T.Northeast]	5.402e+04	1.05e+06	0.051	0.959	-2.01e+06	2.12e+06
Region[T.South]	-1.371e+06	3.29e+05	-4.169	0.000	-2.02e+06	-7.26e+05
Region[T.Southeast]	-1.396e+06	5.33e+05	-2.622	0.009	-2.44e+06	-3.52e+05
Region[T.West]	-3.342e+05	5.62e+05	-0.594	0.552	-1.44e+06	7.69e+05
UID	359.9692	223.908	1.608	0.108	-79.174	799.112
Area	1.753e+04	220.065	79.670	0.000	1.71e+04	1.8e+04
Bedrooms	-4.041e+06	2.44e+05	-16.568	0.000	-4.52e+06	-3.56e+06
Resale	-6.857e+05	6.36e+05	-1.077	0.281	-1.93e+06	5.62e+05
MaintenanceStaff	1.748e+05	4.17e+05	0.420	0.675	-6.42e+05	9.92e+05
Gymnasium	4.907e+05	5.85e+05	0.838	0.402	-6.57e+05	1.64e+06
SwimmingPool	2.091e+06	4.45e+05	4.702	0.000	1.22e+06	2.96e+06
LandscapedGardens	-4.405e+06	3.74e+05	-11.772	0.000	-5.14e+06	-3.67e+06
JoggingTrack	2.64e+05	3.94e+05	0.669	0.503	-5.09e+05	1.04e+06
RainWaterHarvesting	2.278e+06	3.56e+05	6.401	0.000	1.58e+06	2.98e+06
IndoorGames	4.98e+05	3.12e+05	1.596	0.111	-1.14e+05	1.11e+06
ShoppingMall	3.067e+06	5.23e+05	5.867	0.000	2.04e+06	4.09e+06
Intercom	9.915e+05	3.46e+05	2.868	0.004	3.13e+05	1.67e+06
SportsFacility	2.387e+04	3.54e+05	0.067	0.946	-6.7e+05	7.18e+05
ATM	-1.744e+06	4.99e+05	-3.494	0.000	-2.72e+06	-7.65e+05
ClubHouse	8.309e+04	4e+05	0.208	0.836	-7.02e+05	8.68e+05
School	-2.869e+06	8.69e+05	-3.302	0.001	-4.57e+06	-1.17e+06
X24X7Security	6.814e+04	4.14e+05	0.164	0.869	-7.45e+05	8.81e+05
PowerBackup	1.534e+06	5.81e+05	2.638	0.008	3.93e+05	2.67e+06
CarParking	9.283e+05	3.19e+05	2.910	0.004	3.03e+05	1.55e+06
StaffQuarter	3.714e+05	4.35e+05	0.854	0.393	-4.82e+05	1.22e+06
Cafeteria	-1.738e+06	3.31e+05	-5.258	0.000	-2.39e+06	-1.09e+06
MultipurposeRoom	-1.152e+06	3.23e+05	-3.567	0.000	-1.79e+06	-5.19e+05
Hospital	-1.448e+06	1.06e+06	-1.372	0.170	-3.52e+06	6.23e+05
WashingMachine	7.739e+05	4.49e+05	1.723	0.085	-1.07e+05	1.65e+06
Gasconnection	-6.601e+05	4.99e+05	-1.324	0.186	-1.64e+06	3.18e+05
AC	-1.202e+06	1.97e+06	-0.609	0.543	-5.07e+06	2.67e+06
Wifi	9.339e-10	3.02e-10	3.089	0.002	3.41e-10	1.53e-09
Childrensplayarea	-1.139e+06	4.56e+05	-2.498	0.013	-2.03e+06	-2.45e+05
LiftAvailable	-2.053e+06	4.15e+05	-4.951	0.000	-2.87e+06	-1.24e+06
BED	-4.282e+06	1.88e+06	-2.281	0.023	-7.96e+06	-6.01e+05
VaastuCompliant	-9.852e+05	3.39e+05	-2.908	0.004	-1.65e+06	-3.21e+05
Microwave	7.739e+05	4.49e+05	1.723	0.085	-1.07e+05	1.65e+06
GolfCourse	-2.782e+06	6.58e+05	-4.231	0.000	-4.07e+06	-1.49e+06
TV	7.739e+05	4.49e+05	1.723	0.085	-1.07e+05	1.65e+06
DiningTable	7.739e+05	4.49e+05	1.723	0.085	-1.07e+05	1.65e+06
Sofa	7.739e+05	4.49e+05	1.723	0.085	-1.07e+05	1.65e+06
Wardrobe	0	0	nan	nan	0	0
Refrigerator	7.739e+05	4.49e+05	1.723	0.085	-1.07e+05	1.65e+06
Furniture	-2.734e+06	1.55e+06	-1.768	0.077	-5.77e+06	2.99e+05
Fitness	8.732e+04	1.78e+05	0.489	0.625	-2.63e+05	4.37e+05
Appliances	1.894e+06	1.03e+06	1.834	0.067	-1.32e+05	3.92e+06
Entertain	6.884e+05	1.93e+05	3.571	0.000	3.1e+05	1.07e+06
Omnibus:	1616.681	Durbin-Watson:	1.125
Prob(Omnibus):	0.000	Jarque-Bera (JB):	135599.071
Skew:	3.638	Prob(JB):	0.00
Kurtosis:	44.237	Cond. No.	1.08e+16


Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 5.96e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
We run the initial linear regression model with all 45 variables. The model was not as robust as expected. We are going to review the details below. Use our correlation matrix to eliminate variables with high correlation and create a robust smaller model.

1
#run regression and looking at the normality plot
2
​
3
​
4
fig = plt.figure(figsize= (10, 10))
5
ax = fig.add_subplot(111)
6
​
7
normality_plot, stat = stats.probplot(model.resid, plot= plt, rvalue= True)
8
ax.set_title("Probability plot of model residual's", fontsize= 20)
9
ax.set
10
​
11
plt.show()

Next I wanted to see how the number Entertainment features available was spread through the regions. It appears the Northeast has the most by far followed by North and Southeast.

Now I'm comparing the housing sizes and it appears once again the Central is dominating followed by Southeast and North. This is making me wonder if the Northeast is more of a "college town" like atmosposhere with very small housing but lots of entertainment near by.

1.6.1  Initial Linear Regression Model
We contnue to improve the model focusing on a subset of variables based on correlation and the explanation was included above.

1
#Run a complete regression model of all variables
2
​
3
#smf.ols(Price~Area+Region+No..of.Bedrooms+Fitness+Appliances+Furniture+RainWaterHarvesting+School+VaastuCompliant+Intercom+LiftAvailable+ShoppingMall+ATM+PowerBackup+MultipurposeRoom+CarParking+LandscapedGardens,
4
        #data = places).fit()
5
model = smf.ols("Price~Area+Region+Bedrooms+Fitness+Appliances+Furniture+RainWaterHarvesting+School+VaastuCompliant+Intercom+LiftAvailable+ShoppingMall+ATM+PowerBackup+MultipurposeRoom+CarParking+LandscapedGardens",
6
        data = places).fit()
7
model.summary()
OLS Regression Results
Dep. Variable:	Price	R-squared:	0.861
Model:	OLS	Adj. R-squared:	0.860
Method:	Least Squares	F-statistic:	517.9
Date:	Sun, 10 Oct 2021	Prob (F-statistic):	0.00
Time:	16:18:18	Log-Likelihood:	-31232.
No. Observations:	1856	AIC:	6.251e+04
Df Residuals:	1833	BIC:	6.264e+04
Df Model:	22		
Covariance Type:	nonrobust		
coef	std err	t	P>|t|	[0.025	0.975]
Intercept	-7.26e+06	6.68e+05	-10.860	0.000	-8.57e+06	-5.95e+06
Region[T.East]	-1.213e+06	4.57e+05	-2.652	0.008	-2.11e+06	-3.16e+05
Region[T.North]	8.856e+05	4.56e+05	1.944	0.052	-7819.952	1.78e+06
Region[T.Northeast]	-8.932e+04	9.97e+05	-0.090	0.929	-2.04e+06	1.87e+06
Region[T.South]	-9.045e+05	3.16e+05	-2.867	0.004	-1.52e+06	-2.86e+05
Region[T.Southeast]	-1.182e+06	5.02e+05	-2.357	0.019	-2.17e+06	-1.99e+05
Region[T.West]	1.933e+05	5.19e+05	0.372	0.710	-8.24e+05	1.21e+06
Area	1.744e+04	218.881	79.679	0.000	1.7e+04	1.79e+04
Bedrooms	-3.87e+06	2.43e+05	-15.948	0.000	-4.35e+06	-3.39e+06
Fitness	5.621e+05	1.37e+05	4.088	0.000	2.92e+05	8.32e+05
Appliances	2.781e+06	1.93e+06	1.444	0.149	-9.96e+05	6.56e+06
Furniture	-4.711e+06	3.21e+06	-1.468	0.142	-1.1e+07	1.58e+06
RainWaterHarvesting	2.551e+06	3.22e+05	7.913	0.000	1.92e+06	3.18e+06
School	-3.151e+06	5.21e+05	-6.052	0.000	-4.17e+06	-2.13e+06
VaastuCompliant	-1.088e+06	3e+05	-3.626	0.000	-1.68e+06	-4.99e+05
Intercom	1.04e+06	3.29e+05	3.163	0.002	3.95e+05	1.68e+06
LiftAvailable	-2.344e+06	3.9e+05	-6.012	0.000	-3.11e+06	-1.58e+06
ShoppingMall	3.095e+06	5.45e+05	5.680	0.000	2.03e+06	4.16e+06
ATM	-1.676e+06	4.68e+05	-3.579	0.000	-2.59e+06	-7.58e+05
PowerBackup	2.312e+06	5.26e+05	4.395	0.000	1.28e+06	3.34e+06
MultipurposeRoom	-4.551e+05	3.07e+05	-1.482	0.138	-1.06e+06	1.47e+05
CarParking	8.384e+05	2.88e+05	2.908	0.004	2.73e+05	1.4e+06
LandscapedGardens	-4.113e+06	3.32e+05	-12.389	0.000	-4.76e+06	-3.46e+06
Omnibus:	1649.210	Durbin-Watson:	1.113
Prob(Omnibus):	0.000	Jarque-Bera (JB):	146093.125
Skew:	3.743	Prob(JB):	0.00
Kurtosis:	45.815	Cond. No.	5.53e+04


Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.53e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
By reviewing the previous model created with multiple regression, I dropped all the variables with high P values. The improved model that I created shows below and it is my final model. The p value of the overall model is small and ensures that the linear model is appropriate, all the coefficients of the model are largers so we don't have any unwanted effects. The R squared of the model is 86% and given that the model is not overfitted this R squared is optimal. The model that we created had 22 variables. We managed to limit the initial 45 but we will continue with one more step.

1.6.2  Final Linear Regression Model
1
#Final model. Low F statistic. High Rsquared 86%. All P values are small. All coefficients are large
2
model2 = smf.ols("Price~Area+Region+Bedrooms+Fitness+RainWaterHarvesting+School+VaastuCompliant+Intercom+LiftAvailable+ShoppingMall+ATM+PowerBackup+CarParking+LandscapedGardens",
3
        data = places).fit()
4
model2.summary()
OLS Regression Results
Dep. Variable:	Price	R-squared:	0.861
Model:	OLS	Adj. R-squared:	0.860
Method:	Least Squares	F-statistic:	598.9
Date:	Sun, 10 Oct 2021	Prob (F-statistic):	0.00
Time:	16:18:18	Log-Likelihood:	-31235.
No. Observations:	1856	AIC:	6.251e+04
Df Residuals:	1836	BIC:	6.262e+04
Df Model:	19		
Covariance Type:	nonrobust		
coef	std err	t	P>|t|	[0.025	0.975]
Intercept	-7.357e+06	6.57e+05	-11.191	0.000	-8.65e+06	-6.07e+06
Region[T.East]	-1.205e+06	4.57e+05	-2.636	0.008	-2.1e+06	-3.08e+05
Region[T.North]	9.699e+05	4.53e+05	2.141	0.032	8.16e+04	1.86e+06
Region[T.Northeast]	-3.448e+05	9.81e+05	-0.352	0.725	-2.27e+06	1.58e+06
Region[T.South]	-8.826e+05	3.15e+05	-2.799	0.005	-1.5e+06	-2.64e+05
Region[T.Southeast]	-1.14e+06	4.98e+05	-2.287	0.022	-2.12e+06	-1.62e+05
Region[T.West]	2.195e+05	5.17e+05	0.425	0.671	-7.94e+05	1.23e+06
Area	1.744e+04	217.907	80.055	0.000	1.7e+04	1.79e+04
Bedrooms	-3.866e+06	2.43e+05	-15.930	0.000	-4.34e+06	-3.39e+06
Fitness	5.08e+05	1.32e+05	3.845	0.000	2.49e+05	7.67e+05
RainWaterHarvesting	2.473e+06	3.13e+05	7.892	0.000	1.86e+06	3.09e+06
School	-3.196e+06	5.2e+05	-6.141	0.000	-4.22e+06	-2.18e+06
VaastuCompliant	-1.184e+06	2.89e+05	-4.102	0.000	-1.75e+06	-6.18e+05
Intercom	1.12e+06	3.21e+05	3.493	0.000	4.91e+05	1.75e+06
LiftAvailable	-2.315e+06	3.84e+05	-6.023	0.000	-3.07e+06	-1.56e+06
ShoppingMall	3.115e+06	5.44e+05	5.724	0.000	2.05e+06	4.18e+06
ATM	-1.662e+06	4.68e+05	-3.551	0.000	-2.58e+06	-7.44e+05
PowerBackup	2.319e+06	5.26e+05	4.408	0.000	1.29e+06	3.35e+06
CarParking	7.74e+05	2.86e+05	2.706	0.007	2.13e+05	1.33e+06
LandscapedGardens	-4.152e+06	3.3e+05	-12.589	0.000	-4.8e+06	-3.51e+06
Omnibus:	1656.452	Durbin-Watson:	1.109
Prob(Omnibus):	0.000	Jarque-Bera (JB):	147737.611
Skew:	3.768	Prob(JB):	0.00
Kurtosis:	46.053	Cond. No.	1.53e+04


Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.53e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
Here I again want to look at descriptive statistics for the major predictors.

1
places[["Area", "Bedrooms", "Fitness"]].describe()
Area	Bedrooms	Fitness
count	1856.000000	1856.000000	1856.000000
mean	1508.585129	2.522091	3.014009
std	776.867104	0.680532	1.157569
min	525.000000	1.000000	0.000000
25%	1139.000000	2.000000	3.000000
50%	1307.500000	2.000000	3.000000
75%	1590.000000	3.000000	4.000000
max	9900.000000	5.000000	5.000000
1
places_small = places[["Price", "Area", "Fitness", "Bedrooms"]]
2
places_small.head()
Price	Area	Fitness	Bedrooms
0	5599000	1120	0	2
1	7837000	1866	5	3
2	9834000	2235	5	3
3	8298999	1976	5	3
4	8728000	2182	5	3
1.6.3  Zooming into the final model
Focusing only on the variables that are predictors for the prices I further reviewed their correlations I created a heat map and correlation matrix.

1
sns.pairplot(places_small)
<seaborn.axisgrid.PairGrid at 0x22c57833700>

1
#The prices are distorted because of some apartments in the Central regions. May want to review the data to increase the number of bins appropriately
2
plt.hist(places["Price"], bins=300)
(array([ 27.,  79., 127., 189., 202., 147., 160., 149., 116.,  93.,  89.,
         55.,  36.,  52.,  39.,  26.,  11.,  28.,  13.,  13.,  15.,   5.,
          4.,   7.,   4.,   6.,  12.,   3.,   8.,   6.,   6.,   9.,   8.,
          1.,   4.,   6.,   2.,   3.,   5.,   5.,   3.,   7.,   3.,   3.,
          4.,   0.,   2.,   5.,   2.,   3.,   4.,   2.,   2.,   0.,   1.,
          1.,   2.,   3.,   1.,   1.,   1.,   1.,   0.,   0.,   2.,   2.,
          2.,   0.,   0.,   1.,   0.,   4.,   1.,   1.,   1.,   0.,   1.,
          0.,   0.,   0.,   0.,   1.,   1.,   1.,   0.,   0.,   1.,   0.,
          2.,   0.,   0.,   0.,   2.,   0.,   0.,   0.,   1.,   0.,   0.,
          2.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   2.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,
          0.,   0.,   1.]),
 array([2.0960000e+06, 2.7646800e+06, 3.4333600e+06, 4.1020400e+06,
        4.7707200e+06, 5.4394000e+06, 6.1080800e+06, 6.7767600e+06,
        7.4454400e+06, 8.1141200e+06, 8.7828000e+06, 9.4514800e+06,
        1.0120160e+07, 1.0788840e+07, 1.1457520e+07, 1.2126200e+07,
        1.2794880e+07, 1.3463560e+07, 1.4132240e+07, 1.4800920e+07,
        1.5469600e+07, 1.6138280e+07, 1.6806960e+07, 1.7475640e+07,
        1.8144320e+07, 1.8813000e+07, 1.9481680e+07, 2.0150360e+07,
        2.0819040e+07, 2.1487720e+07, 2.2156400e+07, 2.2825080e+07,
        2.3493760e+07, 2.4162440e+07, 2.4831120e+07, 2.5499800e+07,
        2.6168480e+07, 2.6837160e+07, 2.7505840e+07, 2.8174520e+07,
        2.8843200e+07, 2.9511880e+07, 3.0180560e+07, 3.0849240e+07,
        3.1517920e+07, 3.2186600e+07, 3.2855280e+07, 3.3523960e+07,
        3.4192640e+07, 3.4861320e+07, 3.5530000e+07, 3.6198680e+07,
        3.6867360e+07, 3.7536040e+07, 3.8204720e+07, 3.8873400e+07,
        3.9542080e+07, 4.0210760e+07, 4.0879440e+07, 4.1548120e+07,
        4.2216800e+07, 4.2885480e+07, 4.3554160e+07, 4.4222840e+07,
        4.4891520e+07, 4.5560200e+07, 4.6228880e+07, 4.6897560e+07,
        4.7566240e+07, 4.8234920e+07, 4.8903600e+07, 4.9572280e+07,
        5.0240960e+07, 5.0909640e+07, 5.1578320e+07, 5.2247000e+07,
        5.2915680e+07, 5.3584360e+07, 5.4253040e+07, 5.4921720e+07,
        5.5590400e+07, 5.6259080e+07, 5.6927760e+07, 5.7596440e+07,
        5.8265120e+07, 5.8933800e+07, 5.9602480e+07, 6.0271160e+07,
        6.0939840e+07, 6.1608520e+07, 6.2277200e+07, 6.2945880e+07,
        6.3614560e+07, 6.4283240e+07, 6.4951920e+07, 6.5620600e+07,
        6.6289280e+07, 6.6957960e+07, 6.7626640e+07, 6.8295320e+07,
        6.8964000e+07, 6.9632680e+07, 7.0301360e+07, 7.0970040e+07,
        7.1638720e+07, 7.2307400e+07, 7.2976080e+07, 7.3644760e+07,
        7.4313440e+07, 7.4982120e+07, 7.5650800e+07, 7.6319480e+07,
        7.6988160e+07, 7.7656840e+07, 7.8325520e+07, 7.8994200e+07,
        7.9662880e+07, 8.0331560e+07, 8.1000240e+07, 8.1668920e+07,
        8.2337600e+07, 8.3006280e+07, 8.3674960e+07, 8.4343640e+07,
        8.5012320e+07, 8.5681000e+07, 8.6349680e+07, 8.7018360e+07,
        8.7687040e+07, 8.8355720e+07, 8.9024400e+07, 8.9693080e+07,
        9.0361760e+07, 9.1030440e+07, 9.1699120e+07, 9.2367800e+07,
        9.3036480e+07, 9.3705160e+07, 9.4373840e+07, 9.5042520e+07,
        9.5711200e+07, 9.6379880e+07, 9.7048560e+07, 9.7717240e+07,
        9.8385920e+07, 9.9054600e+07, 9.9723280e+07, 1.0039196e+08,
        1.0106064e+08, 1.0172932e+08, 1.0239800e+08, 1.0306668e+08,
        1.0373536e+08, 1.0440404e+08, 1.0507272e+08, 1.0574140e+08,
        1.0641008e+08, 1.0707876e+08, 1.0774744e+08, 1.0841612e+08,
        1.0908480e+08, 1.0975348e+08, 1.1042216e+08, 1.1109084e+08,
        1.1175952e+08, 1.1242820e+08, 1.1309688e+08, 1.1376556e+08,
        1.1443424e+08, 1.1510292e+08, 1.1577160e+08, 1.1644028e+08,
        1.1710896e+08, 1.1777764e+08, 1.1844632e+08, 1.1911500e+08,
        1.1978368e+08, 1.2045236e+08, 1.2112104e+08, 1.2178972e+08,
        1.2245840e+08, 1.2312708e+08, 1.2379576e+08, 1.2446444e+08,
        1.2513312e+08, 1.2580180e+08, 1.2647048e+08, 1.2713916e+08,
        1.2780784e+08, 1.2847652e+08, 1.2914520e+08, 1.2981388e+08,
        1.3048256e+08, 1.3115124e+08, 1.3181992e+08, 1.3248860e+08,
        1.3315728e+08, 1.3382596e+08, 1.3449464e+08, 1.3516332e+08,
        1.3583200e+08, 1.3650068e+08, 1.3716936e+08, 1.3783804e+08,
        1.3850672e+08, 1.3917540e+08, 1.3984408e+08, 1.4051276e+08,
        1.4118144e+08, 1.4185012e+08, 1.4251880e+08, 1.4318748e+08,
        1.4385616e+08, 1.4452484e+08, 1.4519352e+08, 1.4586220e+08,
        1.4653088e+08, 1.4719956e+08, 1.4786824e+08, 1.4853692e+08,
        1.4920560e+08, 1.4987428e+08, 1.5054296e+08, 1.5121164e+08,
        1.5188032e+08, 1.5254900e+08, 1.5321768e+08, 1.5388636e+08,
        1.5455504e+08, 1.5522372e+08, 1.5589240e+08, 1.5656108e+08,
        1.5722976e+08, 1.5789844e+08, 1.5856712e+08, 1.5923580e+08,
        1.5990448e+08, 1.6057316e+08, 1.6124184e+08, 1.6191052e+08,
        1.6257920e+08, 1.6324788e+08, 1.6391656e+08, 1.6458524e+08,
        1.6525392e+08, 1.6592260e+08, 1.6659128e+08, 1.6725996e+08,
        1.6792864e+08, 1.6859732e+08, 1.6926600e+08, 1.6993468e+08,
        1.7060336e+08, 1.7127204e+08, 1.7194072e+08, 1.7260940e+08,
        1.7327808e+08, 1.7394676e+08, 1.7461544e+08, 1.7528412e+08,
        1.7595280e+08, 1.7662148e+08, 1.7729016e+08, 1.7795884e+08,
        1.7862752e+08, 1.7929620e+08, 1.7996488e+08, 1.8063356e+08,
        1.8130224e+08, 1.8197092e+08, 1.8263960e+08, 1.8330828e+08,
        1.8397696e+08, 1.8464564e+08, 1.8531432e+08, 1.8598300e+08,
        1.8665168e+08, 1.8732036e+08, 1.8798904e+08, 1.8865772e+08,
        1.8932640e+08, 1.8999508e+08, 1.9066376e+08, 1.9133244e+08,
        1.9200112e+08, 1.9266980e+08, 1.9333848e+08, 1.9400716e+08,
        1.9467584e+08, 1.9534452e+08, 1.9601320e+08, 1.9668188e+08,
        1.9735056e+08, 1.9801924e+08, 1.9868792e+08, 1.9935660e+08,
        2.0002528e+08, 2.0069396e+08, 2.0136264e+08, 2.0203132e+08,
        2.0270000e+08]),
 <BarContainer object of 300 artists>)

Based on heatmap it appears that the number of bedrooms and total area within the housing are the most important factors in the pricing. The number of bedrooms has a moderate impact. The number of fitness centers have almost no impact.

1
sns.heatmap(places_small.corr(), annot=True)
<AxesSubplot:>

1.6.4  Conclusion of Multi Linear Regression Model
I started with lots of data and some of it was messy. But after cleaning it up a bit and performing the exploritory data analysis I was able to see strong trends. One is particular was how much more expensive it is to be in the central region compared to everywhere else. I can get a sense of income levels and what types of areas these are but not totally conclusive. There is more work I can do to find that out. But housing prices are strongly tied to the size of a home and the area it's located. There are several other factors such as number of bedrooms that have a moderat impact and others like fitness centers in the area that have almost no impact. Also some area have a much higher degree of variance in prices than others.

1.7  Part 2: Machine Learning
1.7.1  Data Preparation for Machine Learning Algorithms
At this point I'm preparing the data and especially the categorical values for a logistic regression. I'm going to use the dummy method to introduce binary artificial valriables for each one of our categorical variables.

1
dummies = pd.get_dummies(places["Region"])
2
dummies.head()
Central	East	North	Northeast	South	Southeast	West
0	1	0	0	0	0	0	0
1	1	0	0	0	0	0	0
2	1	0	0	0	0	0	0
3	1	0	0	0	0	0	0
4	1	0	0	0	0	0	0
1
dummies = pd.get_dummies(places["Location"])
2
dummies.head()
Amruthahalli	Anagalapura Near Hennur Main Road	Anekal City	Anjanapura	Attibele	Avalahalli Off Sarjapur Road	BTM Layout	Badamanavarthekaval	Banashankari	Banaswadi	...	Talaghattapura	Thanisandra	Uttarahalli	Uttarahalli Hobli	Varthur	Vidyaranyapura	Whitefield	Whitefield Hope Farm Junction	Yelahanka	Yerthiganahalli
0	1	0	0	0	0	0	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0
1	0	1	0	0	0	0	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0
2	0	1	0	0	0	0	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0
3	0	1	0	0	0	0	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0
4	0	1	0	0	0	0	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0
5 rows × 102 columns

1
dummies = pd.get_dummies(places["Resale"])
2
dummies.head()
0	1
0	1	0
1	1	0
2	1	0
3	1	0
4	1	0
1.7.2  Logistic Regression
Response variable "Region" identifying predictors. I will start my machine learning part of the project trying to verify the results of the previous work. My goal here is to build a process that learns the region where a property is located using all the other variables including the price of the properties. The region is a qualitative variable with 7 different values. We have already seen that the prices on some of the regions overlap and predicting prices based on the ammenities of the properties was not easy. What I'd like to do here is to reveal any possible predictors (ammenities) or price that would identify the region of the property. For this purpose I will use a logistic regression.

We prepare to run a logistric regression. Our response variable is the region. We are going to develope a model based on the data received. It will predict the region that the property lays.

1
places1 = places.drop(['UID', 'Region'], axis=1)
2
places1.head()
Price	Area	Location	Bedrooms	Resale	MaintenanceStaff	Gymnasium	SwimmingPool	LandscapedGardens	JoggingTrack	...	GolfCourse	TV	DiningTable	Sofa	Wardrobe	Refrigerator	Furniture	Fitness	Appliances	Entertain
0	5599000	1120	Amruthahalli	2	0	0	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0
1	7837000	1866	Anagalapura Near Hennur Main Road	3	0	0	1	1	1	1	...	1	0	0	0	0	0	0	5	0	3
2	9834000	2235	Anagalapura Near Hennur Main Road	3	0	0	1	1	1	1	...	1	0	0	0	0	0	0	5	0	3
3	8298999	1976	Anagalapura Near Hennur Main Road	3	0	0	1	1	1	1	...	1	0	0	0	0	0	0	5	0	3
4	8728000	2182	Anagalapura Near Hennur Main Road	3	0	0	1	1	1	1	...	1	0	0	0	0	0	0	5	0	3
5 rows × 44 columns

1
places2 = places.drop(['UID'], axis=1)
2
X = pd.concat([places2._get_numeric_data(),dummies],axis=1)
3
y = places2.Region
4
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=1)
1
# build scaler based on training data and apply it to test data to then also scale the test data
2
scaler = preprocessing.StandardScaler().fit(X_train)
3
X_train_scaled=scaler.transform(X_train)
4
X_test_scaled=scaler.transform(X_test)
1
clf = RandomForestClassifier(n_estimators=100, random_state = 1,n_jobs=-1)
2
model_res = clf.fit(X_train_scaled, y_train)
3
y_pred = model_res.predict(X_test_scaled)
4
y_pred_prob = model_res.predict_proba(X_test_scaled)
5
lr_probs = y_pred_prob[:,1]
6
ac = accuracy_score(y_test, y_pred)
7
​
8
f1 = f1_score(y_test, y_pred, average='weighted')
9
cm = confusion_matrix(y_test, y_pred)
10
​
11
print('Random Forest: Accuracy=%.3f' % (ac))
12
​
13
print('Random Forest: f1-score=%.3f' % (f1))
Random Forest: Accuracy=0.935
Random Forest: f1-score=0.935
1
class_names=['North', 'East', 'South', 'West', 'Northeast', 'Southeast', 'Central']
1
def plot_confusion_matrix(cm, classes,
2
                          normalize=False,
3
                          title='Confusion matrix',
4
                          cmap=plt.cm.Blues):
5
    """
6
    This function prints and plots the confusion matrix.
7
    Normalization can be applied by setting `normalize=True`.
8
    """
9
    if normalize:
10
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
11
        print("Normalized confusion matrix")
12
    else:
13
        print('Confusion matrix, without normalization')
14
​
15
    print(cm)
16
​
17
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
18
    plt.title(title)
19
    plt.colorbar()
20
    tick_marks = np.arange(len(classes))
21
    plt.xticks(tick_marks, classes, rotation=45)
22
    plt.yticks(tick_marks, classes)
23
​
24
    fmt = '.2f' if normalize else 'd'
25
    thresh = cm.max() / 2.
26
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
27
        plt.text(j, i, format(cm[i, j], fmt),
28
                 horizontalalignment="center",
29
                 color="white" if cm[i, j] > thresh else "black")
30
​
31
    plt.ylabel('True label')
32
    plt.xlabel('Predicted label')
33
    plt.tight_layout()
34
​
35
​
36
# Compute confusion matrix
37
cnf_matrix = confusion_matrix(y_test, y_pred)
38
np.set_printoptions(precision=2)
39
​
40
# Plot non-normalized confusion matrix
41
plt.figure()
42
plot_confusion_matrix(cnf_matrix, classes=class_names,
43
                      title='Confusion matrix, without normalization')
44
#plt.savefig('figures/RF_cm_multi_class.png')
45
​
46
# Plot normalized confusion matrix
47
plt.figure()
48
plot_confusion_matrix(cnf_matrix, classes=class_names, normalize=True,
49
                      title='Normalized confusion matrix')
50
#plt.savefig('figures/RF_cm_proportion_multi_class.png', bbox_inches="tight")
51
plt.show()
Confusion matrix, without normalization
[[ 85   1   0   0   6   0   1]
 [  1  33   2   0   2   0   0]
 [  3   0  29   0   0   0   0]
 [  0   0   0   5   0   0   0]
 [  2   1   0   0 120   0   1]
 [  0   0   0   0   0  28   0]
 [  1   0   0   0   3   0  48]]
Normalized confusion matrix
[[0.91 0.01 0.   0.   0.06 0.   0.01]
 [0.03 0.87 0.05 0.   0.05 0.   0.  ]
 [0.09 0.   0.91 0.   0.   0.   0.  ]
 [0.   0.   0.   1.   0.   0.   0.  ]
 [0.02 0.01 0.   0.   0.97 0.   0.01]
 [0.   0.   0.   0.   0.   1.   0.  ]
 [0.02 0.   0.   0.   0.06 0.   0.92]]


1
feature_importance = clf.feature_importances_
2
# make importances relative to max importance
3
feature_importance = 100.0 * (feature_importance / feature_importance.max())[:30]
4
sorted_idx = np.argsort(feature_importance)[:30]
5
​
6
pos = np.arange(sorted_idx.shape[0]) + .5
7
print(pos.size)
8
sorted_idx.size
9
plt.figure(figsize=(10,10))
10
plt.barh(pos, feature_importance[sorted_idx], align='center')
11
plt.yticks(pos, X.columns[sorted_idx])
12
plt.xlabel('Relative Importance')
13
plt.title('Variable Importance')
14
plt.show()
30

1.7.2.1  Conclusion of Logistic Regression
I ran a logistic regressio to predict the region of a given apartment/house using the set of 40 variables. The results were quite interesting and had a very high accuracy of 93.5%. The main predictor of the region is the price of the apartment. Although somebody would expect the area to also be one of the most important predictors this doesn't seem to be the case. We can see that variables that define if a region is cosmopolitan area are the ones that are good predictors.

1.7.3  Linear Regression of the price with Gradient Boosting
I'm going to run an OLS, a linear regression model with gradient boosting. The model will learn to predict prices based on the most important variables. Initially it runs with the prices of all the properties. The learned model gave me standard outliers in our predictions. In order to make the model more accurate and not dependant on outliers I reviewed the prices and identified 117 extreme outliers. This was less than 6% of the total observations. I decided to drop the outliers from the initial model and run the learning without them.

1
temp = places['Price']
2
print(temp)
3
temp.sort_values()
0        5599000
1        7837000
2        9834000
3        8298999
4        8728000
          ...   
1851    10600000
1852     9200000
1853    10100000
1854    10300000
1855     9799000
Name: Price, Length: 1856, dtype: int64
45       2096000
201      2157000
511      2253000
523      2254000
522      2254000
         ...    
700    170000000
687    170600000
688    182300000
697    198600000
699    202700000
Name: Price, Length: 1856, dtype: int64
1
Q1 = temp.quantile(0.25)
2
Q3 = temp.quantile(0.75)
3
IQR = Q3 - Q1
4
print(IQR)
4669750.0
1
sum((temp<(Q1 - 3 * IQR))|(temp>(Q3 + 3 * IQR)))
2
threshold  = Q3 + 3 * IQR
3
print(threshold)
23576500.0
1
sns.boxplot(x=temp)
<AxesSubplot:xlabel='Price'>

1
placesClean = places[places['Price'] < threshold]
2
placesClean.head()
UID	Price	Area	Location	Region	Bedrooms	Resale	MaintenanceStaff	Gymnasium	SwimmingPool	...	GolfCourse	TV	DiningTable	Sofa	Wardrobe	Refrigerator	Furniture	Fitness	Appliances	Entertain
0	341	5599000	1120	Amruthahalli	Central	2	0	0	0	0	...	0	0	0	0	0	0	0	0	0	0
1	304	7837000	1866	Anagalapura Near Hennur Main Road	Central	3	0	0	1	1	...	1	0	0	0	0	0	0	5	0	3
2	305	9834000	2235	Anagalapura Near Hennur Main Road	Central	3	0	0	1	1	...	1	0	0	0	0	0	0	5	0	3
3	306	8298999	1976	Anagalapura Near Hennur Main Road	Central	3	0	0	1	1	...	1	0	0	0	0	0	0	5	0	3
4	307	8728000	2182	Anagalapura Near Hennur Main Road	Central	3	0	0	1	1	...	1	0	0	0	0	0	0	5	0	3
5 rows × 46 columns

1
dummies = pd.get_dummies(placesClean["Region"])
2
X_all = placesClean.drop(["UID", "Location", "Region", "Wifi", "Appliances", "Wardrobe", "Price"],axis=1)
3
y = placesClean.Price
4
​
5
​
6
X = pd.concat([X_all,dummies], axis=1)
7
# Create constants for X, so the model knows its bounds
8
X = sm.add_constant(X)
9
​
10
# Split the data
11
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.5, random_state = 123)
12
print(X)
      const  Area  Bedrooms  Resale  MaintenanceStaff  Gymnasium  \
0       1.0  1120         2       0                 0          0   
1       1.0  1866         3       0                 0          1   
2       1.0  2235         3       0                 0          1   
3       1.0  1976         3       0                 0          1   
4       1.0  2182         3       0                 0          1   
...     ...   ...       ...     ...               ...        ...   
1851    1.0  1635         3       0                 0          1   
1852    1.0  1475         3       0                 0          1   
1853    1.0  1560         3       0                 0          1   
1854    1.0  1620         3       0                 0          1   
1855    1.0  1274         2       0                 0          1   

      SwimmingPool  LandscapedGardens  JoggingTrack  RainWaterHarvesting  ...  \
0                0                  0             0                    0  ...   
1                1                  1             1                    1  ...   
2                1                  1             1                    1  ...   
3                1                  1             1                    1  ...   
4                1                  1             1                    1  ...   
...            ...                ...           ...                  ...  ...   
1851             1                  1             0                    0  ...   
1852             1                  1             0                    0  ...   
1853             1                  1             0                    0  ...   
1854             1                  1             0                    0  ...   
1855             1                  0             0                    0  ...   

      Furniture  Fitness  Entertain  Central  East  North  Northeast  South  \
0             0        0          0        1     0      0          0      0   
1             0        5          3        1     0      0          0      0   
2             0        5          3        1     0      0          0      0   
3             0        5          3        1     0      0          0      0   
4             0        5          3        1     0      0          0      0   
...         ...      ...        ...      ...   ...    ...        ...    ...   
1851          0        3          1        0     0      1          0      0   
1852          0        3          1        0     0      1          0      0   
1853          0        3          1        0     0      1          0      0   
1854          0        3          1        0     0      1          0      0   
1855          3        3          1        1     0      0          0      0   

      Southeast  West  
0             0     0  
1             0     0  
2             0     0  
3             0     0  
4             0     0  
...         ...   ...  
1851          0     0  
1852          0     0  
1853          0     0  
1854          0     0  
1855          0     0  

[1739 rows x 47 columns]
1
rModel3 = sm.OLS(y_train, X_train).fit()
2
# Fit the model
3
#rModel3_results = rModel3.fit()
4
print(rModel3.summary())
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.779
Model:                            OLS   Adj. R-squared:                  0.769
Method:                 Least Squares   F-statistic:                     79.17
Date:                Sun, 10 Oct 2021   Prob (F-statistic):          3.31e-244
Time:                        16:18:28   Log-Likelihood:                -13754.
No. Observations:                 869   AIC:                         2.758e+04
Df Residuals:                     831   BIC:                         2.776e+04
Df Model:                          37                                         
Covariance Type:            nonrobust                                         
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
const               -3.312e+06   3.56e+05     -9.315      0.000   -4.01e+06   -2.61e+06
Area                 9229.4578    298.190     30.952      0.000    8644.163    9814.752
Bedrooms            -9.351e+05   1.69e+05     -5.546      0.000   -1.27e+06   -6.04e+05
Resale              -8.546e+05   3.53e+05     -2.424      0.016   -1.55e+06   -1.63e+05
MaintenanceStaff     5.227e+05   2.52e+05      2.077      0.038    2.88e+04    1.02e+06
Gymnasium            1.792e+05   3.31e+05      0.541      0.589   -4.71e+05    8.29e+05
SwimmingPool         6.632e+05   2.44e+05      2.713      0.007    1.83e+05    1.14e+06
LandscapedGardens   -8.228e+05   2.24e+05     -3.678      0.000   -1.26e+06   -3.84e+05
JoggingTrack        -2.157e+05   2.16e+05     -0.999      0.318    -6.4e+05    2.08e+05
RainWaterHarvesting  5.015e+05   2.02e+05      2.489      0.013    1.06e+05    8.97e+05
IndoorGames         -3.308e+05   1.77e+05     -1.867      0.062   -6.78e+05    1.69e+04
ShoppingMall         1.802e+06   2.86e+05      6.302      0.000    1.24e+06    2.36e+06
Intercom            -8.176e+04   1.96e+05     -0.417      0.677   -4.67e+05    3.04e+05
SportsFacility        5.36e+04   1.97e+05      0.272      0.786   -3.33e+05    4.41e+05
ATM                 -9.322e+05   2.78e+05     -3.351      0.001   -1.48e+06   -3.86e+05
ClubHouse            9.259e+05   2.21e+05      4.196      0.000    4.93e+05    1.36e+06
School              -2.288e+06   4.66e+05     -4.907      0.000    -3.2e+06   -1.37e+06
X24X7Security        2.286e+05    2.3e+05      0.995      0.320   -2.23e+05     6.8e+05
PowerBackup         -6.999e+05   3.44e+05     -2.033      0.042   -1.38e+06   -2.43e+04
CarParking           2.343e+05   1.76e+05      1.332      0.183   -1.11e+05     5.8e+05
StaffQuarter         1.053e+06   2.57e+05      4.091      0.000    5.48e+05    1.56e+06
Cafeteria           -4.117e+05   1.85e+05     -2.231      0.026   -7.74e+05   -4.95e+04
MultipurposeRoom      3.87e+05   1.87e+05      2.071      0.039    2.03e+04    7.54e+05
Hospital            -1.513e+05   5.76e+05     -0.263      0.793   -1.28e+06    9.79e+05
WashingMachine       6.402e+05   3.72e+05      1.722      0.085   -8.96e+04    1.37e+06
Gasconnection        1.223e+06   2.85e+05      4.290      0.000    6.64e+05    1.78e+06
AC                   7.531e+05   1.35e+06      0.557      0.578    -1.9e+06    3.41e+06
Childrensplayarea   -1.056e+06   2.47e+05     -4.280      0.000   -1.54e+06   -5.72e+05
LiftAvailable         8.14e+05   2.39e+05      3.406      0.001    3.45e+05    1.28e+06
BED                 -2.159e+06   1.29e+06     -1.669      0.095    -4.7e+06     3.8e+05
VaastuCompliant     -3.535e+05   1.91e+05     -1.850      0.065   -7.29e+05    2.16e+04
Microwave            6.402e+05   3.72e+05      1.722      0.085   -8.96e+04    1.37e+06
GolfCourse          -4.923e+05   3.76e+05     -1.310      0.190   -1.23e+06    2.45e+05
TV                   6.402e+05   3.72e+05      1.722      0.085   -8.96e+04    1.37e+06
DiningTable          6.402e+05   3.72e+05      1.722      0.085   -8.96e+04    1.37e+06
Sofa                 6.402e+05   3.72e+05      1.722      0.085   -8.96e+04    1.37e+06
Refrigerator         6.402e+05   3.72e+05      1.722      0.085   -8.96e+04    1.37e+06
Furniture           -8.784e+05   5.96e+05     -1.473      0.141   -2.05e+06    2.92e+05
Fitness               1.88e+05   9.94e+04      1.892      0.059   -7086.742    3.83e+05
Entertain            2946.0036   1.09e+05      0.027      0.978   -2.11e+05    2.17e+05
Central              2.896e+05   1.69e+05      1.712      0.087   -4.25e+04    6.22e+05
East                -4.567e+05   2.31e+05     -1.977      0.048    -9.1e+05   -3347.496
North                7.288e+05   2.11e+05      3.448      0.001    3.14e+05    1.14e+06
Northeast           -1.178e+06   4.77e+05     -2.470      0.014   -2.11e+06   -2.42e+05
South               -7.353e+05   1.48e+05     -4.976      0.000   -1.03e+06   -4.45e+05
Southeast           -1.143e+06   2.56e+05     -4.464      0.000   -1.65e+06    -6.4e+05
West                -8.181e+05   2.47e+05     -3.318      0.001    -1.3e+06   -3.34e+05
==============================================================================
Omnibus:                      139.282   Durbin-Watson:                   2.089
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              518.657
Skew:                           0.723   Prob(JB):                    2.37e-113
Kurtosis:                       6.498   Cond. No.                     1.25e+17
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.1e-25. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
1
model = LinearRegression()
2
model.fit(X_train, y_train)
3
print(model.coef_)
4
pd.DataFrame(model.coef_, X.columns, columns = ['Coeff'])
5
predictions = model.predict(X_test)
6
​
7
​
[-1.36e-08  9.23e+03 -9.35e+05 -8.55e+05  5.23e+05  1.79e+05  6.63e+05
 -8.23e+05 -2.16e+05  5.02e+05 -3.31e+05  1.80e+06 -8.18e+04  5.36e+04
 -9.32e+05  9.26e+05 -2.29e+06  2.29e+05 -7.00e+05  2.34e+05  1.05e+06
 -4.12e+05  3.87e+05 -1.51e+05  6.40e+05  1.22e+06  7.53e+05 -1.06e+06
  8.14e+05 -2.16e+06 -3.53e+05  6.40e+05 -4.92e+05  6.40e+05  6.40e+05
  6.40e+05  6.40e+05 -8.78e+05  1.88e+05  2.95e+03  7.63e+05  1.65e+04
  1.20e+06 -7.04e+05 -2.62e+05 -6.70e+05 -3.45e+05]
1
metrics.mean_absolute_error(y_test, predictions)
1352160.9274540052
Using a learning rate of 0.5 we get a mean absolute error of 1.35 x10^6 that is a good error since our min apartment price is around $10 million.

1.7.3.1  Visualizing our predictions

1
fig = plt.figure(figsize= (10, 10))
2
ax = fig.add_subplot(111)
3
ax.set_title("Prediction of Property Prices", fontsize= 20)
4
ax.set
5
ax.hist(y_test - predictions, color ='maroon', bins=10, edgecolor="white")
6
plt.xlabel("Price in Millions")
7
plt.ylabel("Properties")
8
​
9
plt.show()
10
​

